### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by En0tS** [N3kas/AdvancedEnchantments#106]
[Server thread/ERROR]: Could not pass event e to AdvancedEnchantments v4.1.4
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at n3kas.ae.libs.h.a(h.java) [AdvancedEnchantments-4.1.4.jar:?]
	at sun.reflect.GeneratedMethodAccessor632.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:413) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.EntityPlayer.die(EntityPlayer.java:432) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:956) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:759) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:586) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.EntityMonster.B(EntityMonster.java:68) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.EntityZombie.B(EntityZombie.java:202) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.PathfinderGoalMeleeAttack.a(SourceFile:127) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.PathfinderGoalMeleeAttack.e(SourceFile:119) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.PathfinderGoalZombieAttack.e(SourceFile:28) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.PathfinderGoalSelector.a(SourceFile:129) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.EntityInsentient.doTick(EntityInsentient.java:664) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.EntityLiving.n(EntityLiving.java:2097) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.EntityInsentient.n(EntityInsentient.java:507) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.EntityMonster.n(EntityMonster.java:24) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.EntityZombie.n(EntityZombie.java:155) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1946) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:246) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.EntityMonster.B_(EntityMonster.java:28) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1631) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1601) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1435) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:668) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
	at n3kas.ae.enchanttypes.r.a(r.java) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor492.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-642f6d2-57ab4cf]
	... 39 more

**Comment by N3kas** [comment]
Seems like you're trying to use an effect which is not designed for that enchant type.
