### ISSUE TITLE
Particles

### ISSUE THREAD

**Issue by Xetchup** [N3kas/AdvancedEnchantments#137]
When using the  PARTICLE effect it is not particles but effects. 

[14:55:16 INFO]: [AdvancedEnchantments] ºcFailed to show 'REDSTONE' particle
[14:55:16 WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.Effect.REDSTONE
[14:55:16 WARN]:        at java.lang.Enum.valueOf(Unknown Source)
[14:55:16 WARN]:        at n3kas.ae.useful.a.a(a.java)
[14:55:16 WARN]:        at n3kas.ae.effectsreader.h.e(h.java)
[14:55:16 WARN]:        at n3kas.ae.effectsreader.h.a(h.java)
[14:55:16 WARN]:        at n3kas.ae.enchanthandler.e.run(e.java)
[14:55:16 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[14:55:16 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349)
[14:55:16 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:785)
[14:55:16 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[14:55:16 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715)
[14:55:16 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618)
[14:55:16 WARN]:        at java.lang.Thread.run(Unknown Source)

You're using [EFFECTS ](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Effect.html)instead of [PARTICLES](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html)

**Comment by N3kas** [comment]
Since you're on 4 year old version reflection is using Effect as it was better supported. Find the same particle on Effect list and use the name from there.

**Comment by Xetchup** [comment]
If you look at the lists EFFECTS is not for particles. There are only a few particles on there and I don't know how EFFECT is better supported, particles are still getting updated with the latest versions of spigot so there should be no problem changing it to particles for addition particles. If you like the EFFECTS you could have support for both but when using particles the PARTICLE enums are clearly the better choice.

**Comment by N3kas** [comment]
I'm not the one to critique someone else but as you're doing it to me you should get your facts right. First off, Particle is not even available until 1.9 release, 1.7 & 1.8 only offered Effect, which is what I'm using via reflection to support the server platform you're literally using it on. If you find particles missing for 1.8 feel free to update **your** server to 1.9, when my reflection in plugin switches to Particle rather than using Effect enums.

Yes they are getting support and updates for 1.13, because that's the last thing left for particles.
