### ISSUE TITLE
console spamming

### ISSUE THREAD

**Issue by signition** [N3kas/AdvancedEnchantments#178]
```
[17:33:38] [Server thread/ERROR]: Could not pass event i to AdvancedEnchantments v4.5.5
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at n3kas.ae.libs.k.a(k.java) [AdvancedEnchantments-4.5.5.jar:?]
	at sun.reflect.GeneratedMethodAccessor1100.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:413) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.EntityPlayer.die(EntityPlayer.java:432) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:956) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:759) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:586) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.EntityMonster.B(EntityMonster.java:68) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.EntityVex$a.e(EntityVex.java:258) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.PathfinderGoalSelector.a(SourceFile:129) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.EntityInsentient.doTick(EntityInsentient.java:664) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.EntityLiving.n(EntityLiving.java:2097) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.EntityInsentient.n(EntityInsentient.java:507) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.EntityMonster.n(EntityMonster.java:24) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1946) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.EntityInsentient.B_(EntityInsentient.java:246) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.EntityMonster.B_(EntityMonster.java:28) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.EntityVex.B_(EntityVex.java:30) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1631) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1601) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1435) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:668) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
	at n3kas.ae.enchanttypes.o.b(o.java) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor936.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-fbe3046]
	... 36 more
```

**Comment by N3kas** [comment]
Fixed
