### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Sonnysboy** [N3kas/AdvancedEnchantments#191]
[22:29:42 INFO]: AdvancedEnchantments caught an error with an action involving inventories
>
[22:29:42 WARN]: java.lang.NullPointerException
>
[22:29:42 WARN]: 	at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:324)
>
[22:29:42 WARN]: 	at n3kas.ae.enchanter.b.a(b.java)
>
[22:29:42 WARN]: 	at n3kas.ae.enchanter.b.a(b.java)
>
[22:29:42 WARN]: 	at n3kas.ae.globallisteners.b.a(b.java)
>
[22:29:42 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>
[22:29:42 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>
[22:29:42 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>
[22:29:42 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
>
[22:29:42 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
>
[22:29:42 WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
>
[22:29:42 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
>
[22:29:42 WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
>
[22:29:42 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
>
[22:29:42 WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1693)
>
[22:29:42 WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31)
>
[22:29:42 WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9)
>
[22:29:42 WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
>
[22:29:42 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>
[22:29:42 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>
[22:29:42 WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
>
[22:29:42 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
>
[22:29:42 WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
>
[22:29:42 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
>
[22:29:42 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
>
[22:29:42 WARN]: 	at java.lang.Thread.run(Thread.java:748)
>
No idea what causes it.

Happens when i do /e /enchanter or other reasons that are unknown to me

**Comment by N3kas** [comment]
Missing enchanter configuration
