### ISSUE TITLE
Error messages spamming console

### ISSUE THREAD

**Issue by Zoneman1972** [N3kas/AdvancedEnchantments#192]
08.11 23:29:14 [Server] ERROR Could not pass event PlayerInteractEvent to AdvancedEnchantments v4.6.2
08.11 23:29:14 [Server] INFO org.bukkit.event.EventException: null
08.11 23:29:14 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
08.11 23:29:14 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
08.11 23:29:14 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
08.11 23:29:14 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
08.11 23:29:14 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:298) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
08.11 23:29:14 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:265) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
08.11 23:29:14 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:110) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
08.11 23:29:14 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1169) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
08.11 23:29:14 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
08.11 23:29:14 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
08.11 23:29:14 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
08.11 23:29:14 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
08.11 23:29:14 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
08.11 23:29:14 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
08.11 23:29:14 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
08.11 23:29:14 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
08.11 23:29:14 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
08.11 23:29:14 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
08.11 23:29:14 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
08.11 23:29:14 [Server] INFO Caused by: java.lang.NullPointerException

**Comment by Sonnysboy** [comment]
Plugin isnt made for 1.13.2 I think

**Comment by N3kas** [comment]
Find the first error (like this one) in your logs after server starts and post it here. This isn't the full error since it was 'spamming'

**Comment by Zoneman1972** [comment]
[05:32:23] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to AdvancedEnchantments v4.6.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:298) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:265) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:110) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1169) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
	at n3kas.ae.enchanttypes.a.a(a.java) ~[AdvancedEnchantments-4.6.2.jar:?]
	at sun.reflect.GeneratedMethodAccessor215.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	... 18 more
[05:32:23] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to AdvancedEnchantments v4.6.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:298) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:265) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:110) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1169) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
	at n3kas.ae.enchanttypes.a.a(a.java) ~[AdvancedEnchantments-4.6.2.jar:?]
	at sun.reflect.GeneratedMethodAccessor215.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	... 18 more
[05:32:23] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to AdvancedEnchantments v4.6.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:298) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:265) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:110) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1169) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
	at n3kas.ae.enchanttypes.a.a(a.java) ~[AdvancedEnchantments-4.6.2.jar:?]
	at sun.reflect.GeneratedMethodAccessor215.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.2.jar:git-Spigot-2474d93-e693496]
	... 18 more

**Comment by GC-spigot** [comment]
Thanks, will try to fix.

**Comment by Zoneman1972** [comment]
Thanks
