### ISSUE TITLE
Error with Shackle

### ISSUE THREAD

**Issue by Devillion** [N3kas/AdvancedEnchantments#26]
Using latest spigot and AE

This posted in game: https://i.imgur.com/RNKO4aj.png

Got this in the console:

`[13:19:29] [Server thread/INFO]: Failed to validate all required parties for effect PULL_CLOSER
[13:19:29] [Server thread/INFO]: Enchantment: shackle, effect: PULL_CLOSER[1.0]
[13:19:29] [Server thread/WARN]: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_12_R1.entity.CraftZombie cannot be cast to org.bukkit.entity.Player
[13:19:29] [Server thread/WARN]: 	at n3kas.ae.effectsreader.b.a(b.java:579)
[13:19:29] [Server thread/WARN]: 	at n3kas.ae.effectsreader.b.a(b.java:84)
[13:19:29] [Server thread/WARN]: 	at n3kas.ae.enchanthandler.c.run(c.java:174)
[13:19:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[13:19:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[13:19:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[13:19:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[13:19:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[13:19:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[13:19:29] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)`

**Comment by N3kas** [comment]
Will be fixed, thanks!
