### ISSUE TITLE
Problem with a bunch of default enchantments

### ISSUE THREAD

**Issue by Samfrog** [N3kas/AdvancedEnchantments#32]
Got this error while testing doublestrike. Latest spigot (regular spigot) & plugin version. 

[14:35:14 WARN]: java.lang.NumberFormatException: For input string: "%damage%"
[14:35:14 WARN]:        at java.lang.NumberFormatException.forInputString(Unknown Source)
[14:35:14 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[14:35:14 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[14:35:14 WARN]:        at n3kas.ae.effectsreader.a.d(a.java:317)
[14:35:14 WARN]:        at n3kas.ae.effectsreader.a.a(a.java:84)
[14:35:14 WARN]:        at n3kas.ae.enchanthandler.d.run(d.java:174)
[14:35:14 WARN]:        at com.massivecraft.massivelag.inject.MassiveLagRunnable.run(MassiveLagRunnable.java:56)
[14:35:14 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[14:35:14 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[14:35:14 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[14:35:14 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[14:35:14 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[14:35:14 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[14:35:14 WARN]:        at java.lang.Thread.run(Unknown Source)

If this is helpful here is a screenshot including a chat msg as well as how the enchantment is configured in enchantments.yml (as well as the console error for good measure)
![bug](https://user-images.githubusercontent.com/25758073/41555807-ce4523e2-7306-11e8-9c41-42c2c5f8f5f8.png)

UPDATE:
it seems its not just this one, some other enchantments are acting up too, such as enrage
![image](https://user-images.githubusercontent.com/25758073/41566508-c1176b62-7329-11e8-9413-fb13df249fe7.png)
![image](https://user-images.githubusercontent.com/25758073/41566517-d1720832-7329-11e8-86ba-94728c19de91.png)

and rage 
![image](https://user-images.githubusercontent.com/25758073/41566558-14cbebb6-732a-11e8-911d-13ad1b579cab.png)

![image](https://user-images.githubusercontent.com/25758073/41566571-1efe05ec-732a-11e8-853d-5a6c93c502e3.png)

**Comment by N3kas** [comment]
Yes I am aware now, I didn't make the configuration and put trust into it. I am going through each enchantment and fixing them all, thank you for informing me!
