### ISSUE TITLE
Error when doing /gkits

### ISSUE THREAD

**Issue by aegood** [N3kas/AdvancedEnchantments#63]
[11:15:03] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to AdvancedEnchantments v4.0.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1154) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
	at n3kas.ae.gkits.g.a(g.java) ~[?:?]
	at n3kas.ae.commands.c.a(c.java) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	... 16 more

**Comment by aegood** [comment]
04.08 15:26:16 [Server] INFO AdvancedEnchantments caught an error with an action involving inventories
04.08 15:26:16 [Server] WARN java.lang.NullPointerException
04.08 15:26:16 [Server] WARN at n3kas.ae.enchantments.e.<init>(e.java)
04.08 15:26:16 [Server] WARN at n3kas.ae.enchantments.a.b(a.java)
04.08 15:26:16 [Server] WARN at n3kas.ae.gkits.f.a(f.java)
04.08 15:26:16 [Server] WARN at n3kas.ae.gkits.c.a(c.java)
04.08 15:26:16 [Server] WARN at n3kas.ae.globallisteners.b.a(b.java)
04.08 15:26:16 [Server] WARN at sun.reflect.GeneratedMethodAccessor272.invoke(Unknown Source)
04.08 15:26:16 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
04.08 15:26:16 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
04.08 15:26:16 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
04.08 15:26:16 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
04.08 15:26:16 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
04.08 15:26:16 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
04.08 15:26:16 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630)
04.08 15:26:16 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31)
04.08 15:26:16 [Server] WARN at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9)
04.08 15:26:16 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
04.08 15:26:16 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
04.08 15:26:16 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04.08 15:26:16 [Server] WARN at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
04.08 15:26:16 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
04.08 15:26:16 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
04.08 15:26:16 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
04.08 15:26:16 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
04.08 15:26:16 [Server] WARN at java.lang.Thread.run(Thread.java:748)

Another error thrown when trying to open the gkit archer.

**Comment by N3kas** [comment]
Resolved (config issue).
