### ISSUE TITLE
InventoryCreativeEvent error.

### ISSUE THREAD

**Issue by En0tS** [N3kas/AdvancedEnchantments#69]
[Server thread/ERROR]: Could not pass event InventoryCreativeEvent to AdvancedEnchantments v4.0.1
org.bukkit.event.EventException: null
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-642f6d2-57ab4cf]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-642f6d2-57ab4cf]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
    at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2045) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
    at net.minecraft.server.v1_12_R1.PacketPlayInSetCreativeSlot.a(SourceFile:23) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
    at net.minecraft.server.v1_12_R1.PacketPlayInSetCreativeSlot.a(SourceFile:9) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
    at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
    at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: n3kas.ae.utils.n: Your current bukkit version seems to be incompatible with this library
    at n3kas.ae.utils.t.c(t.java) ~[?:?]
    at n3kas.ae.utils.t.<init>(t.java) ~[?:?]
    at n3kas.ae.utils.g.a(g.java) ~[?:?]
    at n3kas.ae.useful.a.a(a.java) ~[?:?]
    at n3kas.ae.listeners.b.a(b.java) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor80.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-642f6d2-57ab4cf]
    ... 15 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_12_R1.Packet63WorldParticles
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[spigot.jar:git-Spigot-642f6d2-57ab4cf]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot.jar:git-Spigot-642f6d2-57ab4cf]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_151]
    at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_151]
    at n3kas.ae.utils.m.a(m.java) ~[?:?]
    at n3kas.ae.utils.t.c(t.java) ~[?:?]
    at n3kas.ae.utils.t.<init>(t.java) ~[?:?]
    at n3kas.ae.utils.g.a(g.java) ~[?:?]
    at n3kas.ae.useful.a.a(a.java) ~[?:?]
    at n3kas.ae.listeners.b.a(b.java) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor80.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-642f6d2-57ab4cf]
    ... 15 more

**Comment by N3kas** [comment]
Already has been fixed! Fix will be available for download in next update later today.
