### ISSUE TITLE
WorldGuard

### ISSUE THREAD

**Issue by En0tS** [N3kas/AdvancedEnchantments#91]
spigot 1.12.2, no worldguard.

[Server thread/ERROR]: Error occurred while enabling AdvancedEnchantments v4.1.1 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldguard/protection/flags/Flag
	at n3kas.ae.hooks.b.a(b.java) ~[?:?]
	at n3kas.ae.hooks.b.<init>(b.java) ~[?:?]
	at n3kas.ae.a.onEnable(a.java) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.protection.flags.Flag
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot.jar:git-Spigot-642f6d2-57ab4cf]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	... 14 more

**Comment by N3kas** [comment]
It's detecting that you have a plugin called 'WorldGuard'.

**Comment by En0tS** [comment]
But I don't have WorldGuard on that server.

**Comment by N3kas** [comment]
Possibly fixed, check and if you have any issues open a ticket.
