### ISSUE TITLE
Full inventory check.

### ISSUE THREAD

**Issue by En0tS** [N3kas/AdvancedEnchantments#99]
How about dropping item near the player if his inventory is full?

**Comment by En0tS** [comment]
[13:22:25] [Server thread/INFO]: AdvancedEnchantments caught an error with an action involving inventories
[13:22:25] [Server thread/WARN]: java.lang.NullPointerException
[13:22:25] [Server thread/WARN]: 	at n3kas.ae.nbt.a.b(a.java)
[13:22:25] [Server thread/WARN]: 	at n3kas.ae.items.h.a(h.java)
[13:22:25] [Server thread/WARN]: 	at n3kas.ae.globallisteners.a.a(a.java)
[13:22:25] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
[13:22:25] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:22:25] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[13:22:25] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[13:22:25] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:22:25] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[13:22:25] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[13:22:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2045)
[13:22:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInSetCreativeSlot.a(SourceFile:23)
[13:22:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInSetCreativeSlot.a(SourceFile:9)
[13:22:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[13:22:25] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[13:22:25] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[13:22:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[13:22:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[13:22:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[13:22:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[13:22:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[13:22:25] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by N3kas** [comment]
Will add that, thanks for the suggestion. I'll look into that error as well.

**Comment by N3kas** [comment]
Fixed,
